.PHONY: clean All

All:
	@echo "----------Building project:[ diplom - Debug ]----------"
	@cd "diplom" && "$(MAKE)" -f  "diplom.mk"
clean:
	@echo "----------Cleaning project:[ diplom - Debug ]----------"
	@cd "diplom" && "$(MAKE)" -f  "diplom.mk" clean
